### ISSUE TITLE
Action icon missing

### ISSUE THREAD

**Issue by Rystakei** [cubiq/add-to-homescreen#124]
When the suggestion appears, the action icon appears to be missing when I view this on an iPhone and using the XCode iOS simulator, although it does appear when I emulate an iPhone in Chrome. I've attached a picture of what I see when viewing the simple demo hosted on cubiq.org. 

![missing_action_icon](https://cloud.githubusercontent.com/assets/3893306/4661367/dac99b3a-5522-11e4-9d76-3cdbe1e8af02.png)

**Comment by niftylettuce** [comment]
Getting this issue with iOS simulator 8.1

**Comment by boemska-nik** [comment]
FYI @cubiq adding `.ath-ios10 .ath-action-icon` to the CSS fixes this for me in ios 10
