### ISSUE TITLE
Popup shows on http and https

### ISSUE THREAD

**Issue by mauserrifle** [cubiq/add-to-homescreen#151]
The popup shows on http and https. localStorage is different for https. I see on the net very nasty solutions like:
http://stackoverflow.com/questions/10502469/is-there-any-workaround-to-make-use-of-html5-localstorage-on-both-http-and-https
clearly not really what you would want.

Any clean solution for this (instead pushing the whole site on https)? 

What is the reason this project uses localStorage instead of Cookies?

**Comment by cubiq** [comment]
no particular reason, localstorage is easier to use and doesn't impact performance

**Comment by mauserrifle** [comment]
Ok. I am thinking to make it work with cookies (as an option). 

Thanks for the great project :)

**Comment by mauserrifle** [comment]
I went through all new features. I really like detecting the homescreen :) I decided to only show the popup on one page. With the new detecting features I hope my visitors don't suffer too much popups anymore. Closing this issue. If I still decide to make cookie extension I'll make a issue and pull request by then :)
