### ISSUE TITLE
Show method crashes when OS is unsupported

### ISSUE THREAD

**Issue by martindrapeau** [cubiq/add-to-homescreen#162]
I was trying to test on my laptop and show() crashes when trying to fetch the message. This piece of code does not handle `OS == "unsupported"`:
```
		var message = '';

		if ( this.options.message in ath.intl ) {		// you can force the locale
			message = ath.intl[this.options.message][ath.OS];
		} else if ( this.options.message !== '' ) {		// or use a custom message
			message = this.options.message;
		} else {										// otherwise we use our message
			message = ath.intl[ath.language][ath.OS];
		}
```
You should fail gracefully or default to `"ios"`. Not sure what the best course of action is here.

**Comment by cubiq** [comment]
can we agree on not using the word "crash" :)

**Comment by martindrapeau** [comment]
lol
Its javascript so it doesn't really 'crash' but does trigger an undefined object error on this line because message is `undefined`:
```
message = '<p>' + message.replace('%icon', '<span class="ath-action-icon">icon</span>')
```
You could do this to handle the `"unsupported"` case:
```
message = ath.intl[ath.language][ath.OS 1= "unsupported" ? ath.OS : "ios"];
```
Or have "unsupported" in your ath.intl options. Or replace `"unsupported"` simply with `undefined` and then:
```
message = ath.intl[ath.language][ath.OS || "ios"];
```
Or other options. Point is, `"unsupported"` is a valid `OS` value. So you should handle that case throughout.
Hope this helps :)

**Comment by cubiq** [comment]
I've got the gist and 100% agree. thanks for the report.
