### ISSUE TITLE
had error on line 225

### ISSUE THREAD

**Issue by ilrico** [cubiq/add-to-homescreen#174]
i replaced "options.debug" by "this.options.debug" and no more error

**Comment by nuthinking** [comment]
+1

**Comment by daniel-nalbach** [comment]
I saw this issue in IE11 on v3.2.2 and passing in an empty {} as nuthinking suggested did resolve the issue.

**Comment by peteruithoven** [comment]
I'm having the same issue on Firefox. 

The `ath.Class` function [extends this.options with options](https://github.com/cubiq/add-to-homescreen/blob/master/src/addtohomescreen.js#L223), but then continues to [use options](https://github.com/cubiq/add-to-homescreen/blob/master/src/addtohomescreen.js#L225) (which could be undefined)

**Comment by peteruithoven** [comment]
I was having quite a battle with Github's pull request system, but looks like @cubiq already merged it, awesome! See: https://github.com/cubiq/add-to-homescreen/pull/181
This issue could probably be closed.
