### ISSUE TITLE
Images in css not showing

### ISSUE THREAD

**Issue by michaelgorter** [cubiq/add-to-homescreen#266]
On an up-2-date iphone the image in the popup balloon is not showing. In the original css file the base64 inline encoded png is not working for me. 

For reference: the missing image is action-icon-ios7.png 

Anyone with the same problem, or any tips?
![github-image-missing](https://user-images.githubusercontent.com/31650400/30053750-27ab459c-922a-11e7-94f7-80dd30797784.png)

**Comment by michaelgorter** [comment]
Hmmm... I combined the original css and minified the combined file. If I include this css file separately (uncompressed), the issue is solved.

**Comment by jclimac** [comment]
@michaelgorter please, can you explain a little bit more what you did to solve the issue? I did not understand what css minified and combined means :)

Thanks!!

**Comment by michaelgorter** [comment]
I combined the add-to-homescreen.css to my main css file and compressed (minified) the new "container" css. From that point I was facing the problem of missing images. I decided to rollback and use the css seperately and the problem solved strangely.

**Comment by jclimac** [comment]
Indeed this is very strange. I'm going to give this a shot. Thanks for the explanation!!

**Comment by jclimac** [comment]
Yeah, this is really a strange issue. Did exactly what @michaelgorter did and it solved my problem.

Thanks @michaelgorter !!
