### ISSUE TITLE
Support for Normal Android Browser?

### ISSUE THREAD

**Issue by mj1985** [cubiq/add-to-homescreen#86]
Is it possible to add support for the normal Android Browser, too? I'm not very familiar with all the Android stuff, but it's possible to a homescreen-icon through the star button in the browser and switch the option "Add to" , to "Homescreen".
It's not very different to the normal Chrome Action, just one step more.

PS: I already saw the old and closed issue ticket, but maybe you think about it again :)

**Comment by mhulse** [comment]
> PS: I already saw the old and closed issue ticket, but maybe you think about it again :)

For future readers, I think @mj1985 was referring to issue #15.

Using Android 4.2.2, and an older Samsung device, when I click the hardware settings button, I get "Save to bookmarks" option; from there, I can choose "Add to: Home screen".

Is there any workarounds for getting the android message in the default Browser?

**Comment by mhulse** [comment]
> Are there any workarounds for getting the android message in the default Browser?

As a possible workaround, I've found that I can turn on `debug: true` and then use [browser-sniffing JS to detect if `on-device`](https://gist.github.com/mhulse/a64ac7c3e2f4966bbd74):

```html
<script>
	var classNames = [];
	if (navigator.userAgent.match(/(iPad|iPhone|iPod)/i)) classNames.push('device-ios');
	if (navigator.userAgent.match(/android/i)) classNames.push('device-android');
	var html = document.getElementsByTagName('html')[0];
	if (classNames.length) classNames.push('on-device');
	if (html.classList) html.classList.add.apply(html.classList, classNames);
</script>

<!-- [BEGIN] add-to-homescreen -->
<link rel="stylesheet" href="assets/plugins/addtohomescreen.css">
<script src="assets/plugins/addtohomescreen.min.js"></script>
<script>
// https://github.com/cubiq/add-to-homescreen/issues/86
console.log(classNames.indexOf('on-device'));
if (classNames.indexOf('on-device') > -1) {
	//addToHomescreen.removeSession(); // use this to remove the localStorage variable
	var ath = addToHomescreen({
		debug: true,               // Override browser checks.
		//skipFirstVisit: false,     // Show at first access.
		//displayPace: 0,            // Do not obey the display pace.
		//privateModeOverride: true, // Show the message in private mode.
		//maxDisplayCount: 0         // Do not obey the max display count.
		modal: true,               // Prevents further actions on the website until the message is closed.
		startDelay: 0,             // Display the message right away.
		lifespan: 0                // Do not automatically kill the call out
	});
	//ath.clearSession(); // reset the user session
	//addToHomescreen.removeSession(); // use this to remove the localStorage variable
}
</script>
<!-- [END] add-to-homescreen -->
```

Now it would just be a matter of making the Android message more generic.
